#Solana RPC
SOLANA:
  RPC_URL: "https://api.mainnet-beta.solana.com"
  MAX_FEE_MICRO_LAMPORTS: 250000
  SECURITY_DEPOSIT_APY: 20

#JITO:
#  PUBKEY: "DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL"
#  ENDPOINT: "https://frankfurt.mainnet.block-engine.jito.wtf/api/v1/transactions"
#  STATIC_TIP: 100000

#Bitcoin RPC
BITCOIND:
  PROTOCOL: "http"
  PORT: 8332
  HOST: "127.0.0.1"
  RPC_USERNAME: "user"
  RPC_PASSWORD: "password"
  NETWORK: "mainnet"

#LND RPC
LND:
  CERT_FILE: "~/.lnd/tls.cert"
  MACAROON_FILE: "~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon"
  NODE_HOST: "127.0.0.1"
  NODE_PORT: 10009
#  MNEMONIC_FILE: "./wallet.txt"
#  WALLET_PASSWORD_FILE: "./password.txt"
#  CERT_FILE: "~/.lnd/tls.cert"
#  MACAROON_FILE: "~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon"

#LN setup
LN:
  BASE_FEE: 0.00000010
  FEE_PERCENTAGE: 0.3
  MIN: 0.00001000
  MAX: 0.01000000

  ALLOW_NON_PROBABLE_SWAPS: false
  ALLOW_LN_SHORT_EXPIRY: false

#On-chain setup
ONCHAIN:
  BASE_FEE: 0.00000150
  FEE_PERCENTAGE: 0.3
  MIN: 0.00010000
  MAX: 0.05000000

  NETWORK_FEE_ADD_PERCENTAGE: 25

ASSETS:
  WBTC:
    address: "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"
    decimals: 8
  USDC:
    address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
    decimals: 6
  USDT:
    address: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
    decimals: 6
  WSOL:
    address: "So11111111111111111111111111111111111111112"
    decimals: 9

#SSL:
#  CERT_FILE: "./server.cert"
#  KEY_FILE: "./server.key"

